name: Integration testing
on: push

jobs:
  # Label of the container job
  container-job:
    # Containers must run in Linux based operating systems
    runs-on: ubuntu-latest
    # Docker Hub image that `container-job` executes in
    container: rust

    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      rabbitmq:
        # Docker Hub image
        image: rabbitmq:3.11-management
        env:
          RABBITMQ_DEFAULT_USER: guest
          RABBITMQ_DEFAULT_PASS: guest
        ports:
          - 5672
    steps:
      - name: Checkout provider's code
        uses: actions/checkout@v3
        with:
          path: 'provider'
      - name: Checkout consumer's code
        uses: actions/checkout@v3
        with:
          repository: 'simple0x47/cooplan-definition-consumer'
          path: 'consumer'
      - name: Wait 15 seconds for RabbitMQ service
        run: sleep 15s
        shell: bash
      - name: Run provider in background and consumer
        run: |
          cd provider
          cargo run &
          cd ../
          cd consumer
          cargo run
        env:
          GIT_USERNAME: 'simple0x47'
          GIT_PASSWORD: ${{ secrets.ACCESS_TOKEN }}
          AMQP_CONNECTION_URI: ${{ format('{0}:{1}', 'amqp://guest:guest@127.0.0.1', job.services.rabbitmq.ports['5672']) }}